# Generated by Django 5.0.7 on 2024-07-14 18:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedido_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fecha_entrega',
            field=models.DateField(default=datetime.datetime(2024, 7, 21, 18, 49, 4, 749567, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='fecha_recogida',
            field=models.DateField(default=datetime.datetime(2024, 7, 15, 18, 49, 4, 749567, tzinfo=datetime.timezone.utc)),
        ),
    ]
